apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: testing1
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: container1
        image: httpd
